# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="mother_nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="students.nationality",
                verbose_name="Mother nationality",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="students.nationality",
                verbose_name="Nationality",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.clmround",
                verbose_name="Round",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.school",
                verbose_name="School",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="trainings",
            field=models.ManyToManyField(
                blank=True,
                to="students.training",
                verbose_name="Topics of teacher training",
            ),
        ),
    ]
