# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Makani List", "Makani List"),
                            ("Makani Raw Attendance", "Makani Raw Attendance"),
                            ("Makani Total Attendance", "Makani Total Attendance"),
                            ("Center List", "Center List"),
                            ("Bridging Absence Raw Data", "Bridging Absence Raw Data"),
                            ("Bridging Attendance Total", "Bridging Attendance Total"),
                            (
                                "Bridging Absence Consecutive",
                                "Bridging Absence Consecutive",
                            ),
                            ("Teacher List", "Teacher List"),
                            ("Bridging List", "Bridging List"),
                            ("School List - Bridging", "School List - Bridging"),
                            ("School List", "School List"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Export Type",
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Partner name",
                    ),
                ),
                ("fields", models.JSONField(blank=True, null=True)),
                ("file_format", models.CharField(default="csv", max_length=10)),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export History",
                "verbose_name_plural": "Export History",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("path", models.TextField()),
                ("method", models.CharField(max_length=10)),
                ("data", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
