# Generated by Django 5.2.7 on 2026-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backends", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exporthistory",
            name="export_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    ("NFR Sector List", "NFR Sector List"),
                    ("NFR Sector Raw Attendance", "NFR Sector Raw Attendance"),
                    ("NFR Sector Total Attendance", "NFR Sector Total Attendance"),
                    ("Center List", "Center List"),
                    ("Bridging Absence Raw Data", "Bridging Absence Raw Data"),
                    ("Bridging Attendance Total", "Bridging Attendance Total"),
                    ("Bridging Absence Consecutive", "Bridging Absence Consecutive"),
                    ("Teacher List", "Teacher List"),
                    ("Bridging List", "Bridging List"),
                    ("Bridging Profile IDs", "Bridging Profile IDs"),
                    ("Makani Profile IDs", "Makani Profile IDs"),
                    ("School List - Bridging", "School List - Bridging"),
                    ("School List", "School List"),
                ],
                max_length=100,
                null=True,
                verbose_name="Export Type",
            ),
        ),
    ]
