# Generated by Django 5.2.7 on 2026-09-12 12:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="Device id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Device name",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="App version",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last login"
                    ),
                ),
                (
                    "last_pull",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last pull"
                    ),
                ),
                (
                    "last_push",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last push"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile device",
                "verbose_name_plural": "Mobile devices",
                "ordering": ["-modified"],
                "unique_together": {("user", "device_id")},
            },
        ),
        migrations.CreateModel(
            name="MobileSyncBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Batch uuid"
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="App version",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "item_count",
                    models.PositiveIntegerField(default=0, verbose_name="Items"),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Summary"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_batches",
                        to="mobile_api.mobiledevice",
                        verbose_name="Device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_sync_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile sync batch",
                "verbose_name_plural": "Mobile sync batches",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="MobileSyncItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "client_uuid",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Client uuid"
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Entity"
                    ),
                ),
                (
                    "op",
                    models.CharField(
                        default="create", max_length=16, verbose_name="Operation"
                    ),
                ),
                (
                    "server_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Server id"
                    ),
                ),
                (
                    "parent_uuid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Parent uuid",
                    ),
                ),
                (
                    "parent_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Parent id"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "resolution",
                    models.JSONField(blank=True, null=True, verbose_name="Resolution"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("merged", "Merged"),
                            ("linked", "Linked"),
                            ("duplicate", "Duplicate"),
                            ("conflict", "Conflict"),
                            ("error", "Error"),
                            ("discarded", "Discarded"),
                            ("skipped", "Skipped"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="Message"),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=dict, verbose_name="Errors"),
                ),
                (
                    "duplicates",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Duplicates"
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="Result"),
                ),
                (
                    "duplicate_override",
                    models.BooleanField(
                        default=False, verbose_name="Duplicate override"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="mobile_api.mobilesyncbatch",
                        verbose_name="Batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile sync item",
                "verbose_name_plural": "Mobile sync items",
                "ordering": ["batch", "position"],
                "unique_together": {("batch", "client_uuid")},
            },
        ),
    ]
