# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.contrib.postgres.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("overview", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("assessment_form", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bridging",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "have_labour",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("no", "No"),
                                ("Yes - Morning", "Yes - Morning"),
                                ("Yes - Afternoon", "Yes - Afternoon"),
                                ("Yes - All day", "Yes - All day"),
                            ],
                            max_length=50,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Does the child participate in work?",
                    ),
                ),
                (
                    "labour_weekly_income",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("5 USD or Less", "5 USD or Less"),
                            ("5-20 USD", "5-20 USD"),
                            ("20-50 USD", "20-50 USD"),
                            ("50-100 USD", "50-100 USD"),
                            ("More than 100 USD", "More than 100 USD"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="What is the income of the child per week?",
                    ),
                ),
                (
                    "labours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("", "----------"),
                                ("agriculture", "Agriculture"),
                                ("building", "Building"),
                                ("manufacturing", "Manufacturing"),
                                ("retail_store", "Retail / Store"),
                                ("begging", "Begging"),
                                ("other_many_other", "Other services"),
                            ],
                            max_length=50,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="What is the type of work ?",
                    ),
                ),
                (
                    "labours_single_selection",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("agriculture", "Agriculture"),
                            ("building", "Building"),
                            ("manufacturing", "Manufacturing"),
                            ("retail_store", "Retail / Store"),
                            ("begging", "Begging"),
                            ("other_many_other", "Other services"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="What is the type of work ?",
                    ),
                ),
                (
                    "labours_other_specify",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Please specify(hotel, restaurant, transport, personal services such as cleaning, hair care, cooking and childcare)",
                    ),
                ),
                (
                    "labour_hours",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="How many hours does this child work in a day?",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "enrolled"),
                            ("pre_test", "pre_test"),
                            ("post_test", "post_test"),
                        ],
                        default="enrolled",
                        max_length=50,
                    ),
                ),
                ("pre_test", models.JSONField(default=dict)),
                (
                    "pre_test_score",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Pre-assessment",
                    ),
                ),
                ("post_test", models.JSONField(default=dict)),
                (
                    "post_test_score",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Post-assessment",
                    ),
                ),
                ("scores", models.JSONField(default=dict)),
                (
                    "participation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("no_absence", "No Absence"),
                            ("less_than_5days", "Less than 5 absence days"),
                            ("5_10_days", "5 to 10 absence days"),
                            ("10_15_days", "10 to 15 absence days"),
                            ("15_25_days", "15 to 25 absence days"),
                            ("more_than_25days", "More than 25 absence days"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Participation",
                    ),
                ),
                (
                    "barriers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("", "----------"),
                                (
                                    "Full time job to support family financially",
                                    "Full time job to support family financially",
                                ),
                                ("seasonal_work", "Seasonal work"),
                                (
                                    "availablity_electronic_device",
                                    "Availablity of Electronic Device",
                                ),
                                ("internet_connectivity", "Internet Connectivity"),
                                ("sickness", "Sickness"),
                                ("security", "Security"),
                                ("family_moved", "Family moved"),
                                ("Moved back to Syria", "Moved back to Syria"),
                                (
                                    "Enrolled in formal education",
                                    "Enrolled in formal education",
                                ),
                                (
                                    "marriage engagement pregnancy",
                                    "Marriage/Engagement/Pregnancy",
                                ),
                                ("violence bullying", "Violence/Bullying"),
                                (
                                    "No interest in pursuing the programme/No value",
                                    "No interest in pursuing the programme/No value",
                                ),
                                ("other", "Other"),
                            ],
                            max_length=100,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Barriers",
                    ),
                ),
                (
                    "barriers_single",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            (
                                "Full time job to support family financially",
                                "Full time job to support family financially",
                            ),
                            ("seasonal_work", "Seasonal work"),
                            (
                                "availablity_electronic_device",
                                "Availablity of Electronic Device",
                            ),
                            ("internet_connectivity", "Internet Connectivity"),
                            ("sickness", "Sickness"),
                            ("security", "Security"),
                            ("family_moved", "Family moved"),
                            ("Moved back to Syria", "Moved back to Syria"),
                            (
                                "Enrolled in formal education",
                                "Enrolled in formal education",
                            ),
                            (
                                "marriage engagement pregnancy",
                                "Marriage/Engagement/Pregnancy",
                            ),
                            ("violence bullying", "Violence/Bullying"),
                            (
                                "No interest in pursuing the programme/No value",
                                "No interest in pursuing the programme/No value",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="The main barriers affecting the daily attendance and performance",
                    ),
                ),
                (
                    "barriers_other",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                (
                    "test_done",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="test_done",
                    ),
                ),
                (
                    "round_complete",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="Round complete",
                    ),
                ),
                (
                    "follow_up_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "----------"),
                            ("Phone", "Phone Call"),
                            ("House visit", "House Visit"),
                            ("Family Visit", "Family Visit"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Type of follow up",
                    ),
                ),
                (
                    "phone_call_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Please enter the number phone calls",
                    ),
                ),
                (
                    "house_visit_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Please enter the number of house visits",
                    ),
                ),
                (
                    "family_visit_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Please enter the number parent visits",
                    ),
                ),
                (
                    "phone_call_follow_up_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("child back", "Phone Call"),
                            (
                                "child transfer to difficulty center",
                                "Child transfer to difficulty center",
                            ),
                            (
                                "child transfer to protection",
                                "Child transfer to protection",
                            ),
                            ("child transfer to medical", "Child transfer to medical"),
                            ("Intensive followup", "Intensive followup"),
                            ("dropout", "Dropout"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Result of follow up",
                    ),
                ),
                (
                    "house_visit_follow_up_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("child back", "Phone Call"),
                            (
                                "child transfer to difficulty center",
                                "Child transfer to difficulty center",
                            ),
                            (
                                "child transfer to protection",
                                "Child transfer to protection",
                            ),
                            ("child transfer to medical", "Child transfer to medical"),
                            ("Intensive followup", "Intensive followup"),
                            ("dropout", "Dropout"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Result of follow up",
                    ),
                ),
                (
                    "family_visit_follow_up_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("child back", "Phone Call"),
                            (
                                "child transfer to difficulty center",
                                "Child transfer to difficulty center",
                            ),
                            (
                                "child transfer to protection",
                                "Child transfer to protection",
                            ),
                            ("child transfer to medical", "Child transfer to medical"),
                            ("Intensive followup", "Intensive followup"),
                            ("dropout", "Dropout"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Result of follow up",
                    ),
                ),
                (
                    "cp_referral",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="CP Followup",
                    ),
                ),
                (
                    "parent_attended_visits",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="Parents attended parents meeting",
                    ),
                ),
                (
                    "pss_session_attended",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="Attended PSS Session",
                    ),
                ),
                (
                    "pss_session_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="PSS session number"
                    ),
                ),
                (
                    "pss_session_modality",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("online", "Online via Whatsapp"),
                                ("phone", "Phone calls"),
                                ("offline", "Offline(F2F)"),
                            ],
                            max_length=200,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Please the modality used per each session",
                    ),
                ),
                (
                    "pss_parent_attended",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Parents attended parents meeting",
                    ),
                ),
                (
                    "pss_parent_attended_other",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                (
                    "covid_session_attended",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="Attended PSS Session",
                    ),
                ),
                (
                    "covid_session_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="PSS session number"
                    ),
                ),
                (
                    "covid_session_modality",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("online", "Online via Whatsapp"),
                                ("phone", "Phone calls"),
                                ("offline", "Offline(F2F)"),
                            ],
                            max_length=200,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Please the modality used per each session",
                    ),
                ),
                (
                    "covid_parent_attended",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Parents attended parents meeting",
                    ),
                ),
                (
                    "covid_parent_attended_other",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                (
                    "followup_session_attended",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="Attended PSS Session",
                    ),
                ),
                (
                    "followup_session_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="PSS session number"
                    ),
                ),
                (
                    "followup_session_modality",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("online", "Online via Whatsapp"),
                                ("phone", "Phone calls"),
                                ("offline", "Offline(F2F)"),
                            ],
                            max_length=200,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Please the modality used per each session",
                    ),
                ),
                (
                    "followup_parent_attended",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Parents attended parents meeting",
                    ),
                ),
                (
                    "followup_parent_attended_other",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                (
                    "visits_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Please enter the number parent visits",
                    ),
                ),
                (
                    "child_health_examed",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name='"Did the child receive health exam',
                    ),
                ),
                (
                    "child_health_concern",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="Anything to worry about",
                    ),
                ),
                ("deleted", models.BooleanField(blank=True, default=False)),
                ("dropout_status", models.BooleanField(blank=True, default=False)),
                ("moved", models.BooleanField(blank=True, default=False)),
                (
                    "internal_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Internal number",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Comments"),
                ),
                (
                    "unsuccessful_pretest_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("disability", "Disability"),
                            (
                                "enrolled and did not do the pre-test",
                                "Enrolled and did not do the pre-test",
                            ),
                            ("enrolled in formal", "Enrolled in formal education"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="unsuccessful pre test reason",
                    ),
                ),
                (
                    "unsuccessful_posttest_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("disability", "Disability"),
                            ("dropout", "Dropout from the round"),
                            ("uncompleted_participation", "Uncompleted Participation"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="unsuccessful post test reason",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "phone_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone number confirm",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNHCR Registered", "UNHCR Registered"),
                            ("UNHCR Recorded", "UNHCR Recorded"),
                            ("Syrian national ID", "Syrian national ID"),
                            ("Palestinian national ID", "Palestinian national ID"),
                            ("Lebanese national ID", "Lebanese national ID"),
                            (
                                "Lebanese Extract of Record",
                                "Lebanese Extract of Record",
                            ),
                            ("Other nationality", "Other nationality"),
                            ("Child have no ID", "Child have no ID"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Child ID type",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Case number"
                    ),
                ),
                (
                    "case_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Case number confirm",
                    ),
                ),
                (
                    "individual_case_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Individual Case number",
                    ),
                ),
                (
                    "individual_case_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Individual Case number confirm",
                    ),
                ),
                (
                    "recorded_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Recorded number",
                    ),
                ),
                (
                    "recorded_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Recorded number confirm",
                    ),
                ),
                (
                    "other_nationality",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Specify the nationality",
                    ),
                ),
                (
                    "national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Lebanese ID number ",
                    ),
                ),
                (
                    "national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Lebanese ID number confirm",
                    ),
                ),
                (
                    "parent_extract_record",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Lebanese Extract of Record",
                    ),
                ),
                (
                    "parent_extract_record_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Lebanese Extract of Record confirm",
                    ),
                ),
                (
                    "individual_extract_record",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Lebanese Extract of Record of the child",
                    ),
                ),
                (
                    "individual_extract_record_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Confirm Lebanese Extract of Record of the child",
                    ),
                ),
                (
                    "syrian_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Syrian ID number ",
                    ),
                ),
                (
                    "syrian_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Syrian ID number confirm",
                    ),
                ),
                (
                    "sop_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Palestinian ID number ",
                    ),
                ),
                (
                    "sop_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Palestinian ID number confirm",
                    ),
                ),
                (
                    "source_of_identification_specify",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                (
                    "rims_case_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="RIMS Case Number",
                    ),
                ),
                (
                    "source_of_transportation",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Transportation provided by partner",
                                "Transportation provided by partner",
                            ),
                            ("Walk", "Walk"),
                            ("private or parents", "Private/Parents"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Source of transportation of the child",
                    ),
                ),
                (
                    "no_child_id_confirmation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "no_parent_id_confirmation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "parent_id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNHCR Registered", "UNHCR Registered"),
                            ("UNHCR Recorded", "UNHCR Recorded"),
                            ("Syrian national ID", "Syrian national ID"),
                            ("Palestinian national ID", "Palestinian national ID"),
                            ("Lebanese national ID", "Lebanese national ID"),
                            ("Parent have no ID", "Parent have no ID"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Parent ID type",
                    ),
                ),
                (
                    "parent_case_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Case number"
                    ),
                ),
                (
                    "parent_case_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Case number confirm",
                    ),
                ),
                (
                    "parent_individual_case_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Individual Case number",
                    ),
                ),
                (
                    "parent_individual_case_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Individual Case number confirm",
                    ),
                ),
                (
                    "parent_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Lebanese ID number ",
                    ),
                ),
                (
                    "parent_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Lebanese ID number confirm",
                    ),
                ),
                (
                    "parent_syrian_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Syrian ID number ",
                    ),
                ),
                (
                    "parent_syrian_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Syrian ID number confirm",
                    ),
                ),
                (
                    "parent_sop_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Palestinian ID number ",
                    ),
                ),
                (
                    "parent_sop_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Palestinian ID number confirm",
                    ),
                ),
                (
                    "parent_other_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ID number "
                    ),
                ),
                (
                    "parent_other_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID number confirm",
                    ),
                ),
                (
                    "other_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child ID number ",
                    ),
                ),
                (
                    "other_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child ID number confirm",
                    ),
                ),
                (
                    "referral_programme_type_1",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "CP (PSS and/or Case Management)",
                                "CP (PSS and/or Case Management)",
                            ),
                            ("Health", "Health"),
                            ("WASH", "WASH"),
                            ("Specialized Services", "Specialized Services"),
                            ("Other", "Other"),
                            ("No need", "No need"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Programme Type",
                    ),
                ),
                (
                    "referral_partner_1",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="School / Center",
                    ),
                ),
                (
                    "referral_date_1",
                    models.DateField(
                        blank=True, null=True, verbose_name="Referral date"
                    ),
                ),
                (
                    "confirmation_date_1",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date when the receiving organization confirms accepting the child (or child receiving service)",
                    ),
                ),
                (
                    "referral_programme_type_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "CP (PSS and/or Case Management)",
                                "CP (PSS and/or Case Management)",
                            ),
                            ("Health", "Health"),
                            ("WASH", "WASH"),
                            ("Specialized Services", "Specialized Services"),
                            ("Other", "Other"),
                            ("No need", "No need"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Programme Type",
                    ),
                ),
                (
                    "referral_partner_2",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="School / Center",
                    ),
                ),
                (
                    "referral_date_2",
                    models.DateField(
                        blank=True, null=True, verbose_name="Referral date"
                    ),
                ),
                (
                    "confirmation_date_2",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date when the receiving organization confirms accepting the child (or child receiving service)",
                    ),
                ),
                (
                    "referral_programme_type_3",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "CP (PSS and/or Case Management)",
                                "CP (PSS and/or Case Management)",
                            ),
                            ("Health", "Health"),
                            ("WASH", "WASH"),
                            ("Specialized Services", "Specialized Services"),
                            ("Other", "Other"),
                            ("No need", "No need"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Programme Type",
                    ),
                ),
                (
                    "referral_partner_3",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="School / Center",
                    ),
                ),
                (
                    "referral_date_3",
                    models.DateField(
                        blank=True, null=True, verbose_name="Referral date"
                    ),
                ),
                (
                    "confirmation_date_3",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date when the receiving organization confirms accepting the child (or child receiving service)",
                    ),
                ),
                (
                    "followup_call_reason_1",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
                (
                    "followup_call_result_1",
                    models.TextField(blank=True, null=True, verbose_name="Results"),
                ),
                (
                    "followup_call_date_1",
                    models.DateField(blank=True, null=True, verbose_name="Call date"),
                ),
                (
                    "followup_call_reason_2",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
                (
                    "followup_call_result_2",
                    models.TextField(blank=True, null=True, verbose_name="Results"),
                ),
                (
                    "followup_call_date_2",
                    models.DateField(blank=True, null=True, verbose_name="Call date"),
                ),
                (
                    "followup_visit_reason_1",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
                (
                    "followup_visit_result_1",
                    models.TextField(blank=True, null=True, verbose_name="Results"),
                ),
                (
                    "followup_visit_date_1",
                    models.DateField(blank=True, null=True, verbose_name="Visit date"),
                ),
                (
                    "caretaker_first_name",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Caregiver First Name"
                    ),
                ),
                (
                    "caretaker_middle_name",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Caregiver Middle Name"
                    ),
                ),
                (
                    "caretaker_last_name",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Caregiver Last Name"
                    ),
                ),
                (
                    "caretaker_mother_name",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Caregiver Mother Name"
                    ),
                ),
                (
                    "caretaker_birthday_year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1940", 1940),
                            ("1941", 1941),
                            ("1942", 1942),
                            ("1943", 1943),
                            ("1944", 1944),
                            ("1945", 1945),
                            ("1946", 1946),
                            ("1947", 1947),
                            ("1948", 1948),
                            ("1949", 1949),
                            ("1950", 1950),
                            ("1951", 1951),
                            ("1952", 1952),
                            ("1953", 1953),
                            ("1954", 1954),
                            ("1955", 1955),
                            ("1956", 1956),
                            ("1957", 1957),
                            ("1958", 1958),
                            ("1959", 1959),
                            ("1960", 1960),
                            ("1961", 1961),
                            ("1962", 1962),
                            ("1963", 1963),
                            ("1964", 1964),
                            ("1965", 1965),
                            ("1966", 1966),
                            ("1967", 1967),
                            ("1968", 1968),
                            ("1969", 1969),
                            ("1970", 1970),
                            ("1971", 1971),
                            ("1972", 1972),
                            ("1973", 1973),
                            ("1974", 1974),
                            ("1975", 1975),
                            ("1976", 1976),
                            ("1977", 1977),
                            ("1978", 1978),
                            ("1979", 1979),
                            ("1980", 1980),
                            ("1981", 1981),
                            ("1982", 1982),
                            ("1983", 1983),
                            ("1984", 1984),
                            ("1985", 1985),
                            ("1986", 1986),
                            ("1987", 1987),
                            ("1988", 1988),
                            ("1989", 1989),
                            ("1990", 1990),
                            ("1991", 1991),
                            ("1992", 1992),
                            ("1993", 1993),
                            ("1994", 1994),
                            ("1995", 1995),
                            ("1996", 1996),
                            ("1997", 1997),
                            ("1998", 1998),
                            ("1999", 1999),
                            ("2000", 2000),
                            ("2001", 2001),
                            ("2002", 2002),
                            ("2003", 2003),
                            ("2004", 2004),
                            ("2005", 2005),
                            ("2006", 2006),
                        ],
                        default=0,
                        max_length=4,
                        null=True,
                        verbose_name="Caregiver birthday year",
                    ),
                ),
                (
                    "caretaker_birthday_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "January"),
                            ("2", "February"),
                            ("3", "March"),
                            ("4", "April"),
                            ("5", "May"),
                            ("6", "June"),
                            ("7", "July"),
                            ("8", "August"),
                            ("9", "September"),
                            ("10", "October"),
                            ("11", "November"),
                            ("12", "December"),
                        ],
                        default=0,
                        max_length=2,
                        null=True,
                        verbose_name="Caregiver birthday month",
                    ),
                ),
                (
                    "caretaker_birthday_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", 1),
                            ("2", 2),
                            ("3", 3),
                            ("4", 4),
                            ("5", 5),
                            ("6", 6),
                            ("7", 7),
                            ("8", 8),
                            ("9", 9),
                            ("10", 10),
                            ("11", 11),
                            ("12", 12),
                            ("13", 13),
                            ("14", 14),
                            ("15", 15),
                            ("16", 16),
                            ("17", 17),
                            ("18", 18),
                            ("19", 19),
                            ("20", 20),
                            ("21", 21),
                            ("22", 22),
                            ("23", 23),
                            ("24", 24),
                            ("25", 25),
                            ("26", 26),
                            ("27", 27),
                            ("28", 28),
                            ("29", 29),
                            ("30", 30),
                            ("31", 31),
                        ],
                        default=0,
                        max_length=2,
                        null=True,
                        verbose_name="Caregiver birthday day",
                    ),
                ),
                (
                    "cycle_completed",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Course completed successfully",
                    ),
                ),
                (
                    "enrolled_at_school",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Enrolled at School"
                    ),
                ),
                (
                    "basic_stationery",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Did the child receive basic stationery?",
                    ),
                ),
                (
                    "pss_kit",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Did the child benefit from the PSS kit?",
                    ),
                ),
                (
                    "remote_learning",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Was the child involved in remote learning?",
                    ),
                ),
                (
                    "remote_learning_reasons_not_engaged",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("child_relocated", "Child relocated"),
                            ("child_is_not_reachable", "Child is not reachable"),
                            (
                                "child_did_not_fit_the_criteria",
                                "Child did not fit the criteria - enrolled in previous FE",
                            ),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="what other reasons for this child not being engaged?",
                    ),
                ),
                (
                    "reasons_not_engaged_other",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                (
                    "reliable_internet",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("sometimes", "Sometimes"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Does the family have reliable internet service in their area during remote learning?",
                    ),
                ),
                (
                    "gender_participate",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Did both girls and boys in the same family participate in the class and have access to the phone/device?",
                    ),
                ),
                (
                    "gender_participate_explain",
                    models.TextField(blank=True, null=True, verbose_name="Explain"),
                ),
                (
                    "remote_learning_engagement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hundred", "100%"),
                            ("seventy_five", "75%"),
                            ("fifty", "50%"),
                            ("twenty_five", "25%"),
                            ("less_than_twenty_five", "Less than 25%"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Frequency of Child Engagement in remote learning?",
                    ),
                ),
                (
                    "meet_learning_outcomes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hundred", "100%"),
                            ("seventy_five", "75%"),
                            ("fifty", "50%"),
                            ("twenty_five", "25%"),
                            ("less_than_twenty_five", "Less than 25%"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="How well did the child meet the learning outcomes?",
                    ),
                ),
                (
                    "parent_learning_support_rate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hundred", "100%"),
                            ("seventy_five", "75%"),
                            ("fifty", "50%"),
                            ("twenty_five", "25%"),
                            ("less_than_twenty_five", "Less than 25%"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="How do you rate the parents learning support provided to the child through this Remote learning phase?",
                    ),
                ),
                (
                    "covid_message",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Has the child directly been reached with awareness messaging on Covid-19 and prevention measures?",
                    ),
                ),
                (
                    "covid_message_how_often",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("daily", "Daily"),
                            ("every_2_to_3_days", "Every 2-3 days"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="How often?",
                    ),
                ),
                (
                    "covid_parents_message",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Has the parents directly been reached with awareness messaging on Covid-19 and prevention measures? ",
                    ),
                ),
                (
                    "covid_parents_message_how_often",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("daily", "Daily"),
                            ("every_2_to_3_days", "Every 2-3 days"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="How often?",
                    ),
                ),
                (
                    "follow_up_done",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Was any follow-up done to ensure messages were well received, understood and adopted?",
                    ),
                ),
                (
                    "follow_up_done_with_who",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("child", "Child"),
                            ("caregiver", "Caregiver"),
                            ("child_and_caregiver", "Child and caregiver"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="With who child and/or caregiver?",
                    ),
                ),
                (
                    "child_received_books",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="child received books",
                    ),
                ),
                (
                    "child_received_printout",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="child received printout",
                    ),
                ),
                (
                    "child_received_internet",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="child received internet",
                    ),
                ),
                (
                    "referal_wash",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="referal wash",
                    ),
                ),
                (
                    "referal_health",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="referal health",
                    ),
                ),
                (
                    "referal_other",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=100,
                        null=True,
                        verbose_name="referal other",
                    ),
                ),
                (
                    "referal_other_specify",
                    models.TextField(
                        blank=True, null=True, verbose_name="referal other specify"
                    ),
                ),
                (
                    "akelius_program",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                (
                                    "child using Akelius in Center",
                                    "child using Akelius in Center",
                                ),
                                (
                                    "child using Akelius at Home",
                                    "child using Akelius at Home",
                                ),
                                (
                                    "Child is not using Akelius at all",
                                    "Child is not using Akelius at all",
                                ),
                            ],
                            max_length=200,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Did the child use Akelius program",
                    ),
                ),
                (
                    "miss_school_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="miss_school_date"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("english_arabic", "English/Arabic"),
                            ("french_arabic", "French/Arabic"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="The language supported in the program",
                    ),
                ),
                (
                    "residence_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Informal settlement", "Informal settlement - مخيم"),
                            ("House", "House - منزل"),
                            ("Collective shelter", "Collective shelter - مجمع سكني  "),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Residence Type",
                    ),
                ),
                (
                    "referral",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("from_same_ngo", "Referral from the same NGO"),
                                ("from_other_ngo", "Referral from an other NGO"),
                                (
                                    "form_official_reference",
                                    "Referral from an official reference (Mukhtar, Municipality, School Director, etc.)",
                                ),
                                (
                                    "from_host_community",
                                    "Referral from the host community",
                                ),
                                (
                                    "from_displaced_community",
                                    "Referral from the displaced community",
                                ),
                            ],
                            max_length=100,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Referral",
                    ),
                ),
                (
                    "learning_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            (
                                "graduated_to_Bridging_next_level",
                                "Progress to the next Dirasa level",
                            ),
                            (
                                "graduated_to_Bridging_next_round_same_level",
                                "Repeat the same Dirasa level",
                            ),
                            ("dropout", "Drop out"),
                            ("referred_public_school", "Referred to formal education"),
                            ("other", "Referred to another pathway"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Learning result",
                    ),
                ),
                (
                    "dropout_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dropout reason"
                    ),
                ),
                (
                    "learning_result_other",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please Specify"
                    ),
                ),
                (
                    "referral_school",
                    models.TextField(
                        blank=True, null=True, verbose_name="Formal Education school"
                    ),
                ),
                (
                    "referral_school_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Public", "Public"),
                            ("Private", "Private"),
                            ("Semi-Private", "Semi-Private"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="School Type",
                    ),
                ),
                (
                    "dropout_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dropout date"
                    ),
                ),
                (
                    "first_attendance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="First attendance date"
                    ),
                ),
                (
                    "round_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Round start date"
                    ),
                ),
                (
                    "registration_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("level_one", "Level one"),
                            ("level_two", "Level two"),
                            ("level_three", "Level three"),
                            ("level_four", "Level four"),
                            ("level_five", "Level five"),
                            ("level_six", "Level six"),
                            ("level_one_pm", "Level one PM shift"),
                            ("level_two_pm", "Level two PM shift"),
                            ("level_three_pm", "Level three PM shift"),
                            ("level_four_pm", "Level four PM shift"),
                            ("level_five_pm", "Level five PM shift"),
                            ("level_six_pm", "Level six PM shift"),
                            ("grade_one", "Grade one"),
                            ("grade_two", "Grade two"),
                            ("grade_three", "Grade three"),
                            ("grade_four", "Grade four"),
                            ("grade_five", "Grade five"),
                            ("grade_six", "Grade six"),
                            ("grade_seven", "Grade seven"),
                            ("grade_eight", "Grade eight"),
                            ("grade_nine", "Grade nine"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Registration level",
                    ),
                ),
                (
                    "main_caregiver",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Main Caregiver",
                    ),
                ),
                (
                    "main_caregiver_nationality_other",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="specify"
                    ),
                ),
                (
                    "other_caregiver_relationship",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Other Caregiver Relationship",
                    ),
                ),
                (
                    "student_number_children",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, 0),
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                        ],
                        null=True,
                        verbose_name="How many children does this child have?",
                    ),
                ),
                (
                    "phone_owner",
                    models.CharField(
                        choices=[
                            ("main_caregiver", "Phone Main Caregiver"),
                            ("family member", "Family Member"),
                            ("neighbors", "Neighbors"),
                            ("shawish", "Shawish"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Phone Owner",
                    ),
                ),
                (
                    "second_phone_owner",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("main_caregiver", "Phone Main Caregiver"),
                            ("family member", "Family Member"),
                            ("neighbors", "Neighbors"),
                            ("shawish", "Shawish"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Second Phone Owner",
                    ),
                ),
                (
                    "second_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Second Phone number",
                    ),
                ),
                (
                    "second_phone_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Second Phone number confirm",
                    ),
                ),
                (
                    "source_of_identification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("CP partner referral", "CP partner referral"),
                            ("Awarness Session", "Awarness Session"),
                            ("Child parents", "Child parents"),
                            ("From Profiling Database", "From Profiling Database"),
                            (
                                "Referred by the municipality / Other formal sources",
                                "Referred by the municipality / Other formal sources",
                            ),
                            ("From Displaced Community", "From Displaced Community"),
                            ("From Hosted Community", "From Hosted Community"),
                            ("From Other NGO", "From Other NGO"),
                            ("School Director", "School Director"),
                            ("RIMS", "RIMS"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Source of identification of the child",
                    ),
                ),
                (
                    "education_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            (
                                "No Registered in any school before",
                                "Not Registered in any school before",
                            ),
                            (
                                "Was registered in BLN program",
                                "Was registered in BLN program",
                            ),
                            (
                                "Was registered in formal school and didnt continue",
                                "Was registered in formal school and didnt continue",
                            ),
                            (
                                "Was registered in CBECE program",
                                "Was registered in CBECE program",
                            ),
                            (
                                "Was registered in ALP program and didnt continue",
                                "Was registered in ALP program and didnt continue",
                            ),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Education status",
                    ),
                ),
                (
                    "community_Liaison_follow_up",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Was the community Liaison at school level involved in follow up on child absence or drop out?",
                    ),
                ),
                (
                    "community_liaison_specify",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="specify"
                    ),
                ),
                (
                    "receiving_social_assistance",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Is the child receiving social assistance?",
                    ),
                ),
                (
                    "receiving_transportation_support",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Is the Child Receiving Transportation Support?",
                    ),
                ),
                (
                    "using_digital_platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("yes_akelius)", "Yes (Akelius)"),
                            ("yes_learning_passport)", "Yes (Learning Passport)"),
                            ("no", "No"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Is the Child Using a digital platform (Akelius or  Learning Passport)",
                    ),
                ),
                (
                    "school_contacted_caretaker",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Have the child caregivers been contacted by the School Community Laison",
                    ),
                ),
                (
                    "discussion_topic",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Please specify what has been discussed",
                    ),
                ),
                (
                    "have_labour_single_selection",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no", "No"),
                            ("Yes - Morning", "Yes - Morning"),
                            ("Yes - Afternoon", "Yes - Afternoon"),
                            ("Yes - All day", "Yes - All day"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Does the child participate in work?",
                    ),
                ),
                (
                    "consent_parents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/student",
                        verbose_name="Consent from parents",
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Registration Date"
                    ),
                ),
                ("mid_test1", models.JSONField(default=dict)),
                ("mid_test2", models.JSONField(default=dict)),
                (
                    "enrolled_formal_education",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Was this child enrolled in Formal Education last year and dropped out due to lack of documentation?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bridging",
                "verbose_name_plural": "Bridging",
                "ordering": [
                    "student__first_name",
                    "student__father_name",
                    "student__last_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Site / Center",
                "verbose_name_plural": "Sites / Centers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("current_cycle", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "verbose_name": "Program cycle",
                "verbose_name_plural": "Program cycles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Disability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=145, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Disability",
                "verbose_name_plural": "Disabilities",
                "ordering": ["name"],
            },
        ),
    ]
