# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clm", "0002_initial"),
        ("locations", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bridging",
            name="father_educational_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.educationallevel",
                verbose_name="What is the educational level of the father?",
            ),
        ),
        migrations.AddField(
            model_name="bridging",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.location",
                verbose_name="Governorate",
            ),
        ),
        migrations.AddField(
            model_name="bridging",
            name="hh_educational_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.educationallevel",
                verbose_name="What is the educational level of the mother?",
            ),
        ),
    ]
