# Generated by Django 5.2.7 on 2026-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clm", "0006_alter_bridging_barriers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bridging",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/bridging/profile_pictures",
                verbose_name="Profile picture",
            ),
        ),
    ]
