from __future__ import absolute_import, unicode_literals

from django.urls import re_path

from . import views

app_name = 'schools'

urlpatterns = [
    re_path(
        r'^autocomplete/$',
        view=views.AutocompleteView.as_view(),
        name='autocomplete'
    ),
    re_path(
        r'^school-list/$',
        view=views.SchoolListView.as_view(),
        name='school_list'
    ),
    re_path(
        r'^school-add/$',
        view=views.SchoolAddView.as_view(),
        name='school_add'
    ),
    re_path(
        r'^school-edit/(?P<pk>[\w.@+-]+)/$',
        view=views.SchoolEditView.as_view(),
        name='school_edit'
    ),
    re_path(
        r'^club-list/(?P<school_id>[\w.@+-]+)/$',
        view=views.ClubListView.as_view(),
        name='club_list'
    ),
    re_path(
        r'^club-add/(?P<school_id>[\w.@+-]+)/$',
        view=views.ClubFormView.as_view(),
        name='club_add'
    ),
    re_path(
        r'^club-edit/(?P<school_id>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=views.ClubFormView.as_view(),
        name='club_edit'
    ),
    re_path(
        r'^club-delete/(?P<pk>[\w.@+-]+)/$',
        view=views.club_delete,
        name='club_delete'
    ),
    re_path(
        r'^meeting-list/(?P<school_id>[\w.@+-]+)/$',
        view=views.MeetingListView.as_view(),
        name='meeting_list'
    ),
    re_path(
        r'^meeting-add/(?P<school_id>[\w.@+-]+)/$',
        view=views.MeetingFormView.as_view(),
        name='meeting_add'
    ),
    re_path(
        r'^meeting-edit/(?P<school_id>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=views.MeetingFormView.as_view(),
        name='meeting_edit'
    ),
    re_path(
        r'^meeting-delete/(?P<school_id>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=views.meeting_delete,
        name='meeting_delete'
    ),
    re_path(
        r'^community-initiative-list/(?P<school_id>[\w.@+-]+)/$',
        view=views.CommunityInitiativeListView.as_view(),
        name='community_initiative_list'
    ),
    re_path(
        r'^community-initiative-add/(?P<school_id>[\w.@+-]+)/$',
        view=views.CommunityInitiativeFormView.as_view(),
        name='community_initiative_add'
    ),
    re_path(
        r'^community-initiative-edit/(?P<school_id>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=views.CommunityInitiativeFormView.as_view(),
        name='community_initiative_edit'
    ),
    re_path(
        r'^community-initiative-delete/(?P<pk>[\w.@+-]+)/$',
        view=views.community_initiative_delete,
        name='community_initiative_delete'
    ),
    re_path(
        r'^health-visit-list/(?P<school_id>[\w.@+-]+)/$',
        view=views.HealthVisitListView.as_view(),
        name='health_visit_list'
    ),
    re_path(
        r'^health-visit-add/(?P<school_id>[\w.@+-]+)/$',
        view=views.HealthVisitFormView.as_view(),
        name='health_visit_add'
    ),
    re_path(
        r'^health-visit-edit/(?P<school_id>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=views.HealthVisitFormView.as_view(),
        name='health_visit_edit'
    ),
    re_path(
        r'^health-visit-delete/(?P<pk>[\w.@+-]+)/$',
        view=views.health_visit_delete,
        name='health_visit_delete'
    ),
    re_path(
        'load-districts/$',
        views.load_districts,
        name='load_districts'
    ),
    re_path(
        'load-cadasters/$',
        views.load_cadasters,
        name='load_cadasters'
    ),
    re_path(
        'load-schools/$',
        views.load_schools,
        name='load_schools'
    ),
    re_path(
        r'^school-export-background/$',
        view=views.export_school_background,
        name='school_export_background'
    ),
]
