# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.contrib.postgres.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CLMRound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45, unique=True)),
                ("current_year", models.BooleanField(blank=True, default=False)),
                (
                    "current_round_bridging",
                    models.BooleanField(blank=True, default=False),
                ),
                ("start_date_bridging", models.DateField(blank=True, null=True)),
                ("end_date_bridging", models.DateField(blank=True, null=True)),
                ("start_date_bridging_edit", models.DateField(blank=True, null=True)),
                ("end_date_bridging_edit", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CLM Round",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "club_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Club Name"
                    ),
                ),
                (
                    "number_clubs",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Clubs"
                    ),
                ),
                (
                    "number_children",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Number of Children"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClubType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Club Type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CommunityInitiative",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "community_group_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Community Group Name",
                    ),
                ),
                (
                    "number_initiatives",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Initiatives"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EducationalLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="HealthVisit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Health Focal Point Name",
                    ),
                ),
                (
                    "number_visits",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Visits"
                    ),
                ),
                (
                    "date_first_visit",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of First Visit"
                    ),
                ),
                (
                    "date_last_visit",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Last Visit"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meeting_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Meeting Name",
                    ),
                ),
                (
                    "meeting_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Meeting Date"
                    ),
                ),
                (
                    "number_participants",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Participants"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartnerOrganization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Short Name"
                    ),
                ),
                (
                    "monitoring_evaluation_focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Monitoring and Evaluation Focal Point Name",
                    ),
                ),
                (
                    "monitoring_evaluation_focal_point_phone",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Monitoring and Evaluation Focal Point Phone",
                    ),
                ),
                (
                    "monitoring_evaluation_focal_point_email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Monitoring and Evaluation Focal Point Email",
                    ),
                ),
                (
                    "program_manager_focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Program Manager Focal Point Name",
                    ),
                ),
                (
                    "program_manager_focal_point_phone",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Program Manager Focal Point Phone",
                    ),
                ),
                (
                    "program_manager_focal_point_email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Program Manager Focal Point Email",
                    ),
                ),
                ("active", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PublicHolidays",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=45, unique=True, verbose_name="School CERD Number"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Private School", "Private School"),
                            ("Private Free School", "Private Free School"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="School name")),
                (
                    "director_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="School director name",
                    ),
                ),
                (
                    "land_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="School land phone number",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="School email",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="School GPS (longitude)"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="School GPS (latitude)"
                    ),
                ),
                (
                    "registration_level",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("Level one", "Level one"),
                                ("Level two", "Level two"),
                                ("Level three", "Level three"),
                                ("Level four", "Level four"),
                                ("Level five", "Level five"),
                                ("Level six", "Level six"),
                                ("level_one_pm", "Level one PM shift"),
                                ("level_two_pm", "Level two PM shift"),
                                ("level_three_pm", "Level three PM shift"),
                                ("level_four_pm", "Level four PM shift"),
                                ("level_five_pm", "Level five PM shift"),
                                ("level_six_pm", "Level six PM shift"),
                                ("grade_one", "Grade one"),
                                ("grade_two", "Grade two"),
                                ("grade_three", "Grade three"),
                                ("grade_four", "Grade four"),
                                ("grade_five", "Grade five"),
                                ("grade_six", "Grade six"),
                                ("grade_seven", "Grade seven"),
                                ("grade_eight", "Grade eight"),
                                ("grade_nine", "Grade nine"),
                            ],
                            max_length=200,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Grade level",
                    ),
                ),
                (
                    "school_capacity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="School capacity"
                    ),
                ),
                (
                    "empty_building",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Available empty building/closed campus",
                    ),
                ),
                (
                    "number_children",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (excluding Dirasa)",
                    ),
                ),
                (
                    "number_children_male",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (male)",
                    ),
                ),
                (
                    "number_children_female",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (female)",
                    ),
                ),
                (
                    "number_children_lebanese",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (Lebanese)",
                    ),
                ),
                (
                    "number_children_non_lebanese",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (non Lebanese)",
                    ),
                ),
                (
                    "number_children_sbp",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (Dirasa only)",
                    ),
                ),
                (
                    "number_children_male_sbp",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (male, Dirasa only)",
                    ),
                ),
                (
                    "number_children_female_sbp",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (female, Dirasa only)",
                    ),
                ),
                (
                    "number_children_lebanese_sbp",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (Lebanese, Dirasa only)",
                    ),
                ),
                (
                    "number_children_non_lebanese_sbp",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Number of children enrolled (non Lebanese, Dirasa only)",
                    ),
                ),
                (
                    "CWD_accessible",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Is the school accessible for CWD?",
                    ),
                ),
                (
                    "internet_available",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Availability of Internet",
                    ),
                ),
                (
                    "digital_learning_programme",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Does the school have a digital learning programme?",
                    ),
                ),
                (
                    "school_digital_capacity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of devices"
                    ),
                ),
                (
                    "weekend",
                    models.CharField(
                        blank=True,
                        choices=[("Friday", "Friday"), ("Saturday", "Saturday")],
                        max_length=100,
                        null=True,
                        verbose_name="School weekends",
                    ),
                ),
                (
                    "working_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("Monday", "Monday"),
                                ("Tuesday", "Tuesday"),
                                ("Wednesday", "Wednesday"),
                                ("Thursday", "Thursday"),
                                ("Friday", "Friday"),
                                ("Saturday", "Saturday"),
                                ("Sunday", "Sunday"),
                            ],
                            max_length=100,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Working Days",
                    ),
                ),
                (
                    "academic_year_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="School year start date"
                    ),
                ),
                (
                    "academic_year_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="School year end date"
                    ),
                ),
                (
                    "academic_year_exam_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Exam end date"
                    ),
                ),
                (
                    "director_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="School land phone number",
                    ),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="School fax number",
                    ),
                ),
                (
                    "certified_foreign_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("French", "French"),
                            ("English", "English"),
                            ("French & English", "French & English"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Certified foreign language",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Comments"),
                ),
                (
                    "it_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="School IT name",
                    ),
                ),
                (
                    "it_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="School IT phone number",
                    ),
                ),
                (
                    "attendance_range",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Attendance day range"
                    ),
                ),
                (
                    "attendance_from_beginning",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Start attendance from the beginning",
                    ),
                ),
                (
                    "is_bma",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="BMA school"
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="is closed"
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45, unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
