# Generated by Django 5.2.7 on 2026-04-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerorganization",
            name="dashboard_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Dashboard URL"
            ),
        ),
    ]
