# Generated by Django 5.2.7 on 2026-08-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_school_operating_shift"),
        ("schools", "0004_school_services_programs"),
    ]

    operations = []
