# Generated by Django 5.2.7 on 2026-08-27 10:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alpregistration",
            name="cash_support_programmes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("None", "None"),
                        ("Haddi", "Haddi"),
                        ("Education Cash assistance", "Education Cash assistance"),
                        ("UNHCR cash assistance", "UNHCR cash assistance"),
                        ("WFP cash assistance", "WFP cash assistance"),
                    ],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Cash support programmes that child is already benefiting from",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="deleted",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Deleted"
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="have_labour",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    ("No", "No"),
                    ("Yes - Morning", "Yes - Morning"),
                    ("Yes - Afternoon", "Yes - Afternoon"),
                    ("Yes - Full Day", "Yes - Full day"),
                    ("Yes - Night Shift", "Yes - Night Shift"),
                    ("Yes - Morning & Night Shift", "Yes - Morning & Night Shift"),
                    ("Yes - Afternoon & Night Shift", "Yes - Afternoon & Night Shift"),
                    ("Yes - Full Day & Night Shift", "Yes - Full Day & Night Shift"),
                ],
                max_length=100,
                null=True,
                verbose_name="Does the child participate in work?",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="labour_condition",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Carry heavy loads", "Carry heavy loads"),
                        (
                            "Works in extreme cold, heat or humidity",
                            "Works in extreme cold, heat or humidity",
                        ),
                        (
                            "Exposed to dust, fume or gas",
                            "Exposed to dust, fume or gas",
                        ),
                        (
                            "Maneuvers dangerous tools such as knives or operating heavy machinery",
                            "Maneuvers dangerous tools such as knives or operating heavy machinery",
                        ),
                        (
                            "Required to work with chemicals, such as pesticides, glues and similar, or explosives",
                            "Required to work with chemicals, such as pesticides, glues and similar, or explosives",
                        ),
                        (
                            "Stating exposed to fumes (including argile and cigarettes)  and gas",
                            "Stating exposed to fumes (including argile and cigarettes)  and gas",
                        ),
                        ("Loud noise or vibration", "Loud noise or vibration"),
                        (
                            "Exposed to any other work condition that are bad for his/her health and safety",
                            "Exposed to any other work condition that are bad for his/her health and safety",
                        ),
                    ],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="What is the work condition that the child is exposed to?",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="labour_hours",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of working hours/week ",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="labour_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    ("Agriculture", "Agriculture"),
                    ("Construction", "Construction"),
                    ("Manufacturing", "Manufacturing"),
                    ("Retail / Store", "Retail / Store"),
                    (
                        "Street Connected Work - includes vending and begging",
                        "Street Connected Work - includes vending and begging",
                    ),
                    (
                        "Household chores (includes domestic works and caring for siblings or their caregivers)",
                        "Household chores (includes domestic works and caring for siblings or their caregivers)",
                    ),
                    ("Mechanic shop", "Mechanic shop"),
                    ("Other services", "Other services"),
                    ("Domestic work at other houses", "Domestic work at other houses"),
                    ("In street connected work", "In street connected work"),
                    ("Money exchange", "Money exchange"),
                ],
                max_length=100,
                null=True,
                verbose_name="What is the type of work?",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="labour_type_specify",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Please specify (hotel, restaurant, transport, personal services such as cleaning, hair care, cooking and childcare)",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="labour_weekly_income",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    ("5 USD or Less", "5 USD or Less"),
                    ("5-20 USD", "5-20 USD"),
                    ("20-50 USD", "20-50 USD"),
                    ("50-100 USD", "50-100 USD"),
                    ("More than 100 USD", "More than 100 USD"),
                ],
                max_length=100,
                null=True,
                verbose_name="What is the income of the child per week?",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="mscc_packages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        (
                            "Early Childhood  Development",
                            "Early Childhood  Development",
                        ),
                        ("Education", "Education"),
                        (
                            "Child Protection/Psychosocial support",
                            "Child Protection/Psychosocial support",
                        ),
                        (
                            "Youth Empowerment and engagement",
                            "Youth Empowerment and engagement",
                        ),
                        ("Health and Nutrition", "Health and Nutrition"),
                        (
                            "Parental and Caregiver Support",
                            "Parental and Caregiver Support",
                        ),
                        ("Social Cash Assistance", "Social Cash Assistance"),
                    ],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Packages received/to be provided to child under",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="partner_unique_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Partner unique child number",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="registration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Registration date"
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="source_of_identification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    ("Dirassa", "Dirassa"),
                    ("Awareness Session", "Awareness Session"),
                    ("Child's parents", "Child's parents"),
                    ("From Hosted Community", "From Hosted Community"),
                    (
                        "Sector Partners referral (CP, Education, Health, Wash, Youth, Palestenian program...) ",
                        "Sector Partners referral (CP, Education, Health, Wash, Youth, Palestenian program...) ",
                    ),
                    ("From Profiling Database", "From Profiling Database"),
                    ("From Other NGO", "From Other NGO"),
                    ("From Displaced Community", "From Displaced Community"),
                    (
                        "Referred by the municipality/Other formal sources",
                        "Referred by the municipality/Other formal sources",
                    ),
                    ("Other Sources", "Other Sources"),
                ],
                max_length=100,
                null=True,
                verbose_name="Source of referral of the child",
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="source_of_identification_specify",
            field=models.TextField(
                blank=True, null=True, verbose_name="please specify"
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="student_old",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Student old"
            ),
        ),
        migrations.AddField(
            model_name="alpregistration",
            name="type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Type"
            ),
        ),
        migrations.AlterField(
            model_name="alpregistration",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
