# Generated by Django 5.2.7 on 2026-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alp", "0002_alpregistration_cash_support_programmes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alpteacher",
            name="unicef_id",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="UNIQUE ID"
            ),
        ),
    ]
