# Generated by Django 5.2.7 on 2026-08-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alp", "0003_alp_attendance_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alpattendancechild",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
