# Generated by Django 5.2.7 on 2026-08-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alp", "0002_alpteacher_updates"),
        ("alp", "0004_alter_alpattendancechild_id"),
    ]

    operations = []
