# Generated by Django 5.2.7 on 2026-09-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alp", "0003_alter_alpteacher_teaching_hours_mscc"),
        ("alp", "0008_alter_alpregistration_source_of_identification"),
    ]

    operations = []
