# Generated by Django 5.2.7 on 2026-09-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alp", "0003_alter_alpteacher_teaching_hours_mscc"),
        ("alp", "0009_alpregistration_consent_form"),
    ]

    operations = []
