# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("child", "0003_initial"),
        ("locations", "0001_initial"),
        ("mscc", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationrsservice",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.school",
                verbose_name="Name of public School",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="referred_school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.school",
                verbose_name="Name of the School referred to",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.center",
                verbose_name="Center",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="child",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="child.child",
                verbose_name="Child",
            ),
        ),
    ]
