# Generated by Django 5.2.7 on 2025-11-25 17:24

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_initial"),
        ("mscc", "0004_round_partner"),
        ("students", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="First name",
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Father name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Last name",
                    ),
                ),
                (
                    "mother_fullname",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Mother full name",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=6,
                        null=True,
                        verbose_name="Sex",
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(blank=True, null=True, verbose_name="Birth date"),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=45,
                        null=True,
                        verbose_name="ID number",
                    ),
                ),
                (
                    "unicef_id",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Unicef ID"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "primary_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "subjects_provided",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("arabic", "Arabic"),
                                ("math", "Math"),
                                ("english", "English"),
                                ("french", "French"),
                                ("PSS / Counsellor", "PSS / Counsellor"),
                                ("Physical Education", "Physical Education"),
                                ("Art", "Art"),
                                ("Sciences", "Sciences"),
                                ("PSS", "PSS"),
                                ("History", "History"),
                                ("Geography", "Geography"),
                                ("Civics", "Civics"),
                                ("Computer", "Computer"),
                            ],
                            max_length=200,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Subjects provided",
                    ),
                ),
                (
                    "registration_level",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("Level one", "Level one"),
                                ("Level two", "Level two"),
                                ("Level three", "Level three"),
                                ("Level four", "Level four"),
                                ("Level five", "Level five"),
                                ("Level six", "Level six"),
                                ("level_one_pm", "Level one PM shift"),
                                ("level_two_pm", "Level two PM shift"),
                                ("level_three_pm", "Level three PM shift"),
                                ("level_four_pm", "Level four PM shift"),
                                ("level_five_pm", "Level five PM shift"),
                                ("level_six_pm", "Level six PM shift"),
                                ("grade_one", "Grade one"),
                                ("grade_two", "Grade two"),
                                ("grade_three", "Grade three"),
                                ("grade_four", "Grade four"),
                                ("grade_five", "Grade five"),
                                ("grade_six", "Grade six"),
                                ("grade_seven", "Grade seven"),
                                ("grade_eight", "Grade eight"),
                                ("grade_nine", "Grade nine"),
                            ],
                            max_length=200,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Dirasa Grade level",
                    ),
                ),
                (
                    "teacher_assignment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dirasa only", "Dirasa only"),
                            ("Private and Dirasa", "Private and Dirasa"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Teacher Assignment",
                    ),
                ),
                (
                    "teaching_hours_private_school",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Number of teaching hours in private school",
                    ),
                ),
                (
                    "teaching_hours_mscc",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Number of teaching hours in MSCC",
                    ),
                ),
                (
                    "training_sessions_attended",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, 0),
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                            (23, 23),
                            (24, 24),
                            (25, 25),
                            (26, 26),
                            (27, 27),
                            (28, 28),
                            (29, 29),
                        ],
                        null=True,
                        verbose_name="Number of teacher training sessions (attended)",
                    ),
                ),
                (
                    "extra_coaching",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Extra coaching",
                    ),
                ),
                (
                    "extra_coaching_specify",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                (
                    "attach_short_description_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "attach_file_1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/mscc_teacher",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "attach_short_description_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "attach_file_2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/mscc_teacher",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "attach_short_description_3",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "attach_file_3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/mscc_teacher",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "attach_short_description_4",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "attach_file_4",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/mscc_teacher",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "attach_short_description_5",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "attach_file_5",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/mscc_teacher",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "attach_type_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mscc_attach_type_1",
                        to="students.attachmenttype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "attach_type_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mscc_attach_type_2",
                        to="students.attachmenttype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "attach_type_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mscc_attach_type_3",
                        to="students.attachmenttype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "attach_type_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mscc_attach_type_4",
                        to="students.attachmenttype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "attach_type_5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mscc_attach_type_5",
                        to="students.attachmenttype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="locations.center",
                        verbose_name="Center",
                    ),
                ),
                (
                    "id_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mscc_teachers",
                        to="students.idtype",
                        verbose_name="ID type",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mscc_teachers",
                        to="students.nationality",
                        verbose_name="Nationality",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="mscc.round",
                        verbose_name="Round",
                    ),
                ),
                (
                    "trainings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mscc_teachers",
                        to="students.training",
                        verbose_name="Topics of teacher training",
                    ),
                ),
            ],
            options={
                "verbose_name": "MSCC Teacher",
                "verbose_name_plural": "MSCC Teachers",
            },
        ),
    ]
