# Generated by Django 5.2.7 on 2026-03-26 09:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0005_teacher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ["-id"],
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
            },
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
        migrations.AlterField(
            model_name="educationservice",
            name="education_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    (
                        "Never registered in any formal school before",
                        "Never registered in any formal school before",
                    ),
                    (
                        "Was registered in formal school but didn't continue",
                        "Was registered in formal school but didn't continue",
                    ),
                    (
                        "Was registered in non formal program and was referred",
                        "Was registered in non formal program and was referred",
                    ),
                    (
                        "Was registered in non formal program but didn't continue",
                        "Was registered in non formal program but didn't continue",
                    ),
                    ("Was enrolled in TVET Programs", "Was enrolled in TVET Programs"),
                    (
                        "Was Registered in Formal Education but not attending",
                        "Was Registered in Formal Education but not attending",
                    ),
                    (
                        "Currently registered in Formal Education school",
                        "Currently registered in Formal Education school",
                    ),
                    (
                        "Currently registered in Formal Education school but not attending",
                        "Currently registered in Formal Education school but not attending",
                    ),
                    ("No", "No"),
                ],
                max_length=200,
                null=True,
                verbose_name="Child's educational level when registering for the round",
            ),
        ),
        migrations.AlterField(
            model_name="packages",
            name="type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Type"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="mscc_packages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        (
                            "Early Childhood  Development",
                            "Early Childhood  Development",
                        ),
                        ("Education", "Education"),
                        (
                            "Child Protection/Psychosocial support",
                            "Child Protection/Psychosocial support",
                        ),
                        (
                            "Youth Empowerment and engagement",
                            "Youth Empowerment and engagement",
                        ),
                        ("Health and Nutrition", "Health and Nutrition"),
                        (
                            "Parental and Caregiver Support",
                            "Parental and Caregiver Support",
                        ),
                        ("Social Cash Assistance", "Social Cash Assistance"),
                    ],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Packages received/to be provided to child under",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="source_of_identification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    ("Dirassa", "Dirassa"),
                    ("Awareness Session", "Awareness Session"),
                    ("Child's parents", "Child's parents"),
                    ("From Hosted Community", "From Hosted Community"),
                    (
                        "Sector Partners referral (CP, Education, Health, Wash, Youth, Palestenian program...) ",
                        "Sector Partners referral (CP, Education, Health, Wash, Youth, Palestenian program...) ",
                    ),
                    ("From Profiling Database", "From Profiling Database"),
                    ("From Other NGO", "From Other NGO"),
                    ("From Displaced Community", "From Displaced Community"),
                    (
                        "Referred by the municipality/Other formal sources",
                        "Referred by the municipality/Other formal sources",
                    ),
                    ("Other Sources", "Other Sources"),
                ],
                max_length=100,
                null=True,
                verbose_name="Source of referral of the child",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teaching_hours_mscc",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of teaching hours"
            ),
        ),
        migrations.DeleteModel(
            name="EducationAssessment",
        ),
    ]
