# Generated by Django 5.2.7 on 2026-03-19 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0006_educationprogram_alter_registration_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationprogrammeassessment",
            name="programme_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mscc.educationprogram",
                verbose_name="Education Programme Type",
            ),
        ),
    ]
