# Generated by Django 5.2.7 on 2026-03-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0007_alter_educationprogrammeassessment_programme_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationservice",
            name="education_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mscc.educationprogram",
                verbose_name="Education Program",
            ),
        ),
    ]
