# Generated by Django 5.2.7 on 2026-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0008_alter_educationservice_education_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="packages",
            name="max_age",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Maximum Age"
            ),
        ),
        migrations.AddField(
            model_name="packages",
            name="min_age",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Minimum Age"
            ),
        ),
    ]
