# Generated by Django 5.2.7 on 2026-04-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0009_packages_max_age_packages_min_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="training_date_of_completion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of completion of the training"
            ),
        ),
    ]
