# Generated by Django 5.2.7 on 2026-06-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0011_alter_teacher_unicef_id"),
        ("mscc", "0011_teacher_years_of_experience_and_more"),
    ]

    operations = []
