# Generated by Django 5.2.7 on 2026-08-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0013_alter_referral_recommended_learning_path"),
        ("mscc", "0013_link_teacher_assignment_to_makani"),
    ]

    operations = []
