# Generated by Django 5.2.7 on 2026-08-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0014_merge_20260828_1417"),
        ("mscc", "0014_merge_20260828_1538"),
    ]

    operations = []
