# Generated by Django 5.2.7 on 2026-08-30 12:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0014_merge_20260828_1538"),
        ("schools", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="educationassessment",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="educationhistory",
            name="child",
            field=models.IntegerField(blank=True, null=True, verbose_name="Child"),
        ),
        migrations.AlterField(
            model_name="educationhistory",
            name="programme_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Programme id"
            ),
        ),
        migrations.AlterField(
            model_name="educationhistory",
            name="programme_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Programme type"
            ),
        ),
        migrations.AlterField(
            model_name="educationhistory",
            name="registration_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Registration id"
            ),
        ),
        migrations.AlterField(
            model_name="educationhistory",
            name="student_old",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Student old"
            ),
        ),
        migrations.AlterField(
            model_name="educationprogrammeassessment",
            name="post_test",
            field=models.JSONField(default=dict, verbose_name="Post test"),
        ),
        migrations.AlterField(
            model_name="educationprogrammeassessment",
            name="pre_test",
            field=models.JSONField(default=dict, verbose_name="Pre test"),
        ),
        migrations.AlterField(
            model_name="educationprogrammeassessment",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="educationprogrammeassessment",
            name="school_test",
            field=models.JSONField(default=dict, verbose_name="School test"),
        ),
        migrations.AlterField(
            model_name="educationrsservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="educationservice",
            name="education_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLN Level 1", "BLN Level 1"),
                    ("BLN Level 2", "BLN Level 2"),
                    ("BLN Level 3", "BLN Level 3"),
                    ("YBLN Level 1", "YBLN Level 1"),
                    ("YBLN Level 2", "YBLN Level 2"),
                    ("YBLN Catch-up", "YBLN Catch-up"),
                    ("YFS Level 1", "YFS Level 1"),
                    ("YFS Level 2", "YFS Level 2"),
                    ("YFS Level 1 - RS Grade 9", "YFS Level 1 - RS Grade 9"),
                    ("YFS Level 2 - RS Grade 9", "YFS Level 2 - RS Grade 9"),
                    ("CBECE Level 1", "CBECE Level 1"),
                    ("CBECE Level 2", "CBECE Level 2"),
                    ("CBECE Level 3", "CBECE Level 3"),
                    ("CBECE Catch-up", "CBECE Catch-up"),
                    ("RS Grade 1", "RS Grade 1"),
                    ("RS Grade 2", "RS Grade 2"),
                    ("RS Grade 3", "RS Grade 3"),
                    ("RS Grade 4", "RS Grade 4"),
                    ("RS Grade 5", "RS Grade 5"),
                    ("RS Grade 6", "RS Grade 6"),
                    ("RS Grade 7", "RS Grade 7"),
                    ("RS Grade 8", "RS Grade 8"),
                    ("RS Grade 9", "RS Grade 9"),
                    ("ECD", "ECD"),
                    ("ALP Level 1", "ALP Level 1"),
                    ("ALP Level 2", "ALP Level 2"),
                    ("ALP Level 3", "ALP Level 3"),
                    ("ALP Level 4", "ALP Level 4"),
                ],
                max_length=200,
                null=True,
                verbose_name="Education Program",
            ),
        ),
        migrations.AlterField(
            model_name="educationservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="education_service",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="followupservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="healthnutritionreferral",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="healthnutritionservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="inclusionservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="legoservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="packages",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="packages",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="packages",
            name="required",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Required"
            ),
        ),
        migrations.AlterField(
            model_name="providedservices",
            name="completed",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Completed"
            ),
        ),
        migrations.AlterField(
            model_name="providedservices",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="providedservices",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="providedservices",
            name="required",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Required"
            ),
        ),
        migrations.AlterField(
            model_name="providedservices",
            name="service_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Service id"),
        ),
        migrations.AlterField(
            model_name="pssservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="recreational",
            name="assessment",
            field=models.JSONField(default=dict, verbose_name="Assessment"),
        ),
        migrations.AlterField(
            model_name="recreational",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="dropout_date",
            field=models.DateField(blank=True, null=True, verbose_name="Dropout date"),
        ),
        migrations.AlterField(
            model_name="referral",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="deleted",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Deleted"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="student_old",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Student old"
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="current_year",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Current year"
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="name",
            field=models.CharField(max_length=45, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="roundpartner",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="roundpartner",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="schools.partnerorganization",
                verbose_name="Partner",
            ),
        ),
        migrations.AlterField(
            model_name="roundpartner",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_rounds",
                to="mscc.round",
                verbose_name="Round",
            ),
        ),
        migrations.AlterField(
            model_name="roundpartner",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="registration_level",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Level one", "Level one"),
                        ("Level two", "Level two"),
                        ("Level three", "Level three"),
                        ("Level four", "Level four"),
                        ("Level five", "Level five"),
                        ("Level six", "Level six"),
                    ],
                    max_length=200,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Dirasa Grade level",
            ),
        ),
        migrations.AlterField(
            model_name="youthassessment",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="youthkitservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="youthreferral",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="youthservice",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
        migrations.AlterField(
            model_name="youthservice",
            name="service_values",
            field=models.JSONField(default=dict, verbose_name="Service values"),
        ),
    ]
