# Generated by Django 5.2.7 on 2026-08-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0015_alter_digitalservice_registration_and_more"),
        ("mscc", "0015_merge_20260830_1152"),
    ]

    operations = []
