# Generated by Django 5.2.7 on 2026-10-08 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_center_bma_id'),
        ('mscc', '0016_merge_20260830_1305'),
        ('students', '0004_teacher_years_of_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogrammeassessment',
            name='bma_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='BMA ID'),
        ),
        migrations.AddField(
            model_name='educationservice',
            name='bma_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='BMA ID'),
        ),
        migrations.AddField(
            model_name='referral',
            name='bma_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='BMA ID'),
        ),
        migrations.AddField(
            model_name='registration',
            name='bma_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='BMA registration ID'),
        ),
        migrations.AddField(
            model_name='round',
            name='bma_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='BMA ID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bma_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='BMA Teacher ID'),
        ),
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('bma_id', 'center'), name='mscc_teacher_bma_center_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('bma_id__isnull', True), ('center__isnull', False), _connector='OR'), name='mscc_teacher_bma_needs_center'),
        ),
    ]
