# Generated by Django 5.2.7 on 2026-09-04 09:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscc", "0018_rollback_teacher_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="cash_support_programmes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("None", "No cash support"),
                        ("Haddi", "Haddi"),
                        ("Education Cash assistance", "Education Cash assistance"),
                        ("UNHCR cash assistance", "UNHCR cash assistance"),
                        ("WFP cash assistance", "WFP cash assistance"),
                    ],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Cash support programmes that child is already benefiting from",
            ),
        ),
    ]
