# Generated by Django 5.2.7 on 2026-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0019_registration_informed_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='nfe_programme',
            field=models.CharField(blank=True, choices=[('BLN', 'Basic Literacy and Numeracy (BLN)'), ('DIRASA', 'DIRASA')], max_length=6, null=True, verbose_name='Type of NFE Programme'),
        ),
    ]
