# Generated by Django 5.2.7 on 2026-09-02 14:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncEventLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(unique=True, verbose_name="Event id")),
                (
                    "source_system",
                    models.CharField(
                        db_index=True,
                        default="compiler",
                        max_length=50,
                        verbose_name="Source system",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("mscc.round", "Round"),
                            ("mscc.package", "Package"),
                            ("locations.center", "Center"),
                            ("mscc.teacher", "Teacher"),
                            ("mscc.registration", "Registration"),
                            ("mscc.education_service", "Child education situation"),
                            ("mscc.education_rs_service", "Education RS service"),
                            ("mscc.education_assessment", "Education assessment"),
                            ("mscc.education_grading", "Grading"),
                            ("mscc.referral", "Referral"),
                            ("mscc.pss_service", "PSS service"),
                            ("mscc.inclusion_service", "Inclusion service"),
                            ("mscc.digital_service", "Digital service"),
                            (
                                "mscc.health_nutrition_service",
                                "Health & nutrition service",
                            ),
                            (
                                "mscc.health_nutrition_referral",
                                "Health & nutrition referral",
                            ),
                            ("mscc.youth_kit_service", "Youth kit service"),
                            ("mscc.youth_service", "Youth service"),
                            ("mscc.youth_assessment", "Youth assessment"),
                            ("mscc.youth_referral", "Youth referral"),
                            ("mscc.follow_up_service", "Follow-up service"),
                            ("mscc.recreational", "Recreational"),
                            ("mscc.lego_service", "LEGO service"),
                            ("attendances.mscc_attendance", "Attendance"),
                            ("child.child", "Child"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Resource",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Source primary key"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("upsert", "Create or update"), ("delete", "Delete")],
                        max_length=20,
                        verbose_name="Operation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, null=True, verbose_name="Detail"),
                ),
                (
                    "ignored_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Fields the local model does not have",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "received",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Received at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync event",
                "verbose_name_plural": "Sync events",
                "ordering": ["-received"],
            },
        ),
        migrations.CreateModel(
            name="SyncedRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        db_index=True,
                        default="compiler",
                        max_length=50,
                        verbose_name="Source system",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("mscc.round", "Round"),
                            ("mscc.package", "Package"),
                            ("locations.center", "Center"),
                            ("mscc.teacher", "Teacher"),
                            ("mscc.registration", "Registration"),
                            ("mscc.education_service", "Child education situation"),
                            ("mscc.education_rs_service", "Education RS service"),
                            ("mscc.education_assessment", "Education assessment"),
                            ("mscc.education_grading", "Grading"),
                            ("mscc.referral", "Referral"),
                            ("mscc.pss_service", "PSS service"),
                            ("mscc.inclusion_service", "Inclusion service"),
                            ("mscc.digital_service", "Digital service"),
                            (
                                "mscc.health_nutrition_service",
                                "Health & nutrition service",
                            ),
                            (
                                "mscc.health_nutrition_referral",
                                "Health & nutrition referral",
                            ),
                            ("mscc.youth_kit_service", "Youth kit service"),
                            ("mscc.youth_service", "Youth service"),
                            ("mscc.youth_assessment", "Youth assessment"),
                            ("mscc.youth_referral", "Youth referral"),
                            ("mscc.follow_up_service", "Follow-up service"),
                            ("mscc.recreational", "Recreational"),
                            ("mscc.lego_service", "LEGO service"),
                            ("attendances.mscc_attendance", "Attendance"),
                            ("child.child", "Child"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Resource",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Source primary key"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Local primary key"
                    ),
                ),
                (
                    "last_event_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Last event applied"
                    ),
                ),
                (
                    "last_source_modified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Source modified at"
                    ),
                ),
                (
                    "last_applied_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Values written by the last sync",
                    ),
                ),
                (
                    "local_fingerprint",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Fingerprint of the last sync write",
                    ),
                ),
                (
                    "pending_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Natural keys the last push carried that pointed at records not replicated yet. The target's own handler consults these on arrival.",
                        verbose_name="References to resolve when their target arrives",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Deleted upstream"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Local model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synced record",
                "verbose_name_plural": "Synced records",
                "ordering": ["-modified"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Event id"),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("mscc.round", "Round"),
                            ("mscc.package", "Package"),
                            ("locations.center", "Center"),
                            ("mscc.teacher", "Teacher"),
                            ("mscc.registration", "Registration"),
                            ("mscc.education_service", "Child education situation"),
                            ("mscc.education_rs_service", "Education RS service"),
                            ("mscc.education_assessment", "Education assessment"),
                            ("mscc.education_grading", "Grading"),
                            ("mscc.referral", "Referral"),
                            ("mscc.pss_service", "PSS service"),
                            ("mscc.inclusion_service", "Inclusion service"),
                            ("mscc.digital_service", "Digital service"),
                            (
                                "mscc.health_nutrition_service",
                                "Health & nutrition service",
                            ),
                            (
                                "mscc.health_nutrition_referral",
                                "Health & nutrition referral",
                            ),
                            ("mscc.youth_kit_service", "Youth kit service"),
                            ("mscc.youth_service", "Youth service"),
                            ("mscc.youth_assessment", "Youth assessment"),
                            ("mscc.youth_referral", "Youth referral"),
                            ("mscc.follow_up_service", "Follow-up service"),
                            ("mscc.recreational", "Recreational"),
                            ("mscc.lego_service", "LEGO service"),
                            ("attendances.mscc_attendance", "Attendance"),
                            ("child.child", "Child"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Resource",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Source primary key"
                    ),
                ),
                (
                    "diverged_fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Overwritten values"
                    ),
                ),
                (
                    "acknowledged",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Reviewed"
                    ),
                ),
                (
                    "detected",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Detected at"
                    ),
                ),
                (
                    "synced_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="datasync.syncedrecord",
                        verbose_name="Synced record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync conflict",
                "verbose_name_plural": "Sync conflicts",
                "ordering": ["-detected"],
            },
        ),
        migrations.AddIndex(
            model_name="syncedrecord",
            index=models.Index(
                fields=["resource", "source_id"], name="datasync_sy_resourc_8a583f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedrecord",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="datasync_sy_content_b31849_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncedrecord",
            unique_together={("source_system", "resource", "source_id")},
        ),
    ]
