# Generated by Django 5.2.7 on 2026-10-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='syncedrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='syncedrecord',
            name='source_scope',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='BMA centre ID for teacher identity'),
        ),
        migrations.AlterUniqueTogether(
            name='syncedrecord',
            unique_together={('source_system', 'resource', 'source_id', 'source_scope')},
        ),
    ]
