# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CLMAttendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("round_id", models.IntegerField(blank=True, null=True)),
                (
                    "registration_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("level_one", "Level one"),
                            ("level_two", "Level two"),
                            ("level_three", "Level three"),
                            ("level_four", "Level four"),
                            ("level_five", "Level five"),
                            ("level_six", "Level six"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Registration level",
                    ),
                ),
                (
                    "attendance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Attendance date"
                    ),
                ),
                (
                    "day_off",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Day off ?",
                    ),
                ),
                (
                    "close_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("public_holiday", "Public Holiday"),
                            ("school_holiday", "School Holiday"),
                            ("strike", "Strike"),
                            ("weekly_holiday", "Weekly Holiday"),
                            ("roads_closed", "Roads Closed"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Day off reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirasa Attendance",
                "ordering": ["attendance_date"],
            },
        ),
        migrations.CreateModel(
            name="CLMAttendanceStudent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "attended",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Student Attended?",
                    ),
                ),
                (
                    "absence_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("sick", "Sick"),
                            ("no_transport", "No transport"),
                            ("other", "Other reason"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "absence_reason_other",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="specify"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirasa Student Attendance",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CLMStudentAbsences",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("student_id", models.IntegerField(blank=True, null=True)),
                ("registration_id", models.IntegerField(blank=True, null=True)),
                ("round_id", models.IntegerField(blank=True, null=True)),
                ("partner_id", models.IntegerField(blank=True, null=True)),
                ("school_id", models.IntegerField(blank=True, null=True)),
                (
                    "student_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "student_father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "student_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "registation_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("absence_starting_date", models.DateField(blank=True, null=True)),
                ("absence_ending_date", models.DateField(blank=True, null=True)),
                ("absence_dates", models.JSONField(default=dict)),
                (
                    "consecutive_absence_days",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Dirasa Student Absences",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CLMStudentTotalAttendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("student_id", models.IntegerField(blank=True, null=True)),
                ("registration_id", models.IntegerField(blank=True, null=True)),
                ("round_id", models.IntegerField(blank=True, null=True)),
                ("partner_id", models.IntegerField(blank=True, null=True)),
                ("school_id", models.IntegerField(blank=True, null=True)),
                (
                    "student_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "student_father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "student_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "registation_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("total_attendance_days", models.IntegerField(blank=True, null=True)),
                ("total_absence_days", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Dirasa Student Total Attendance",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MSCCAttendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("round_id", models.IntegerField(blank=True, null=True)),
                (
                    "education_program",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLN Level 1", "BLN Level 1"),
                            ("BLN Level 2", "BLN Level 2"),
                            ("BLN Level 3", "BLN Level 3"),
                            ("BLN Catch-up", "BLN Catch-up"),
                            ("ABLN Level 1", "ABLN Level 1"),
                            ("ABLN Level 2", "ABLN Level 2"),
                            ("ABLN Catch-up", "ABLN Catch-up"),
                            ("YBLN Level 1", "YBLN Level 1"),
                            ("YBLN Level 2", "YBLN Level 2"),
                            ("YBLN Catch-up", "YBLN Catch-up"),
                            ("YFS Level 1", "YFS Level 1"),
                            ("YFS Level 2", "YFS Level 2"),
                            ("YFS Level 1 - RS Grade 9", "YFS Level 1 - RS Grade 9"),
                            ("YFS Level 2 - RS Grade 9", "YFS Level 2 - RS Grade 9"),
                            ("CBECE Level 1", "CBECE Level 1"),
                            ("CBECE Level 2", "CBECE Level 2"),
                            ("CBECE Level 3", "CBECE Level 3"),
                            ("CBECE Catch-up", "CBECE Catch-up"),
                            ("RS Grade 1", "RS Grade 1"),
                            ("RS Grade 2", "RS Grade 2"),
                            ("RS Grade 3", "RS Grade 3"),
                            ("RS Grade 4", "RS Grade 4"),
                            ("RS Grade 5", "RS Grade 5"),
                            ("RS Grade 6", "RS Grade 6"),
                            ("RS Grade 7", "RS Grade 7"),
                            ("RS Grade 8", "RS Grade 8"),
                            ("RS Grade 9", "RS Grade 9"),
                            ("ECD", "ECD"),
                        ],
                        max_length=200,
                        null=True,
                        verbose_name="Education Program",
                    ),
                ),
                (
                    "class_section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Class Section",
                    ),
                ),
                (
                    "attendance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Attendance date"
                    ),
                ),
                (
                    "day_off",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Day off ?",
                    ),
                ),
                (
                    "close_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Public Holiday", "Public Holiday"),
                            ("School Holiday", "School Holiday"),
                            ("Strike", "Strike"),
                            ("Weekly Holiday", "Weekly Holiday"),
                            ("Roads Closed", "Roads Closed"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Day off reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Makani Attendance",
                "ordering": ["attendance_date"],
            },
        ),
        migrations.CreateModel(
            name="MSCCAttendanceChild",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "attended",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("Yes", "Yes"), ("No", "No")],
                        max_length=10,
                        null=True,
                        verbose_name="Child Attended?",
                    ),
                ),
                (
                    "absence_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Sick", "Sick"),
                            ("No transport", "No transport"),
                            ("Other", "Other"),
                            ("Unspecified", "Unspecified"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "absence_reason_other",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="specify"
                    ),
                ),
            ],
            options={
                "verbose_name": "Makani Child Attendance",
                "ordering": ["id"],
            },
        ),
    ]
