# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendances", "0001_initial"),
        ("clm", "0002_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clmattendance",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="clmattendancestudent",
            name="attendance_day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="attendances.clmattendance",
            ),
        ),
        migrations.AddField(
            model_name="clmattendancestudent",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clm.bridging",
                verbose_name="Registration",
            ),
        ),
    ]
