# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendances", "0002_initial"),
        ("child", "0003_initial"),
        ("locations", "0001_initial"),
        ("mscc", "0002_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clmattendancestudent",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="msccattendance",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.center",
                verbose_name="Center",
            ),
        ),
        migrations.AddField(
            model_name="msccattendancechild",
            name="attendance_day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_child",
                to="attendances.msccattendance",
            ),
        ),
        migrations.AddField(
            model_name="msccattendancechild",
            name="child",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="child.child",
                verbose_name="Child",
            ),
        ),
        migrations.AddField(
            model_name="msccattendancechild",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mscc.registration",
                verbose_name="Registration",
            ),
        ),
    ]
