# Generated by Django 5.2.7 on 2026-10-08 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_initial'),
        ('mscc', '0017_educationprogrammeassessment_bma_id_and_more'),
    ]

    operations = [
        # Rename and alter rather than remove/add: existing round IDs survive.
        migrations.RenameField(
            model_name='msccattendance',
            old_name='round_id',
            new_name='round',
        ),
        migrations.AddField(
            model_name='msccattendance',
            name='bma_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='BMA ID'),
        ),
        migrations.AlterField(
            model_name='msccattendance',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mscc.round'),
        ),
    ]
