# Generated by Django 5.2.7 on 2026-03-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendances", "0003_initial"),
        ("mscc", "0006_educationprogram_alter_registration_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msccattendance",
            name="education_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mscc.educationprogram",
                verbose_name="Education Program",
            ),
        ),
    ]
