# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="center_partner",
                to="schools.partnerorganization",
                verbose_name="Partner",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="cadaster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.location",
                verbose_name="Cadaster",
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="caza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.location",
                verbose_name="Caza",
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.location",
                verbose_name="Governorate",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.locationtype",
                verbose_name="Location Type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("name", "type", "p_code")},
        ),
    ]
