# Generated by Django 5.2.7 on 2026-04-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["name"], "verbose_name": "Location"},
        ),
    ]
