# Generated by Django 5.2.7 on 2026-10-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='bma_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='BMA ID'),
        ),
    ]
