# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Last name",
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Father name",
                    ),
                ),
                (
                    "mother_fullname",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Mother fullname",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Male", "Male"),
                            ("Female", "Female"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "nationality_other",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                (
                    "birthday_year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1990", 1990),
                            ("1991", 1991),
                            ("1992", 1992),
                            ("1993", 1993),
                            ("1994", 1994),
                            ("1995", 1995),
                            ("1996", 1996),
                            ("1997", 1997),
                            ("1998", 1998),
                            ("1999", 1999),
                            ("2000", 2000),
                            ("2001", 2001),
                            ("2002", 2002),
                            ("2003", 2003),
                            ("2004", 2004),
                            ("2005", 2005),
                            ("2006", 2006),
                            ("2007", 2007),
                            ("2008", 2008),
                            ("2009", 2009),
                            ("2010", 2010),
                            ("2011", 2011),
                            ("2012", 2012),
                            ("2013", 2013),
                            ("2014", 2014),
                            ("2015", 2015),
                            ("2016", 2016),
                            ("2017", 2017),
                            ("2018", 2018),
                            ("2019", 2019),
                            ("2020", 2020),
                            ("2021", 2021),
                            ("2022", 2022),
                            ("2023", 2023),
                            ("2024", 2024),
                            ("2025", 2025),
                            ("2026", 2026),
                            ("2027", 2027),
                            ("2028", 2028),
                            ("2029", 2029),
                            ("2030", 2030),
                            ("2031", 2031),
                            ("2032", 2032),
                            ("2033", 2033),
                            ("2034", 2034),
                            ("2035", 2035),
                            ("2036", 2036),
                            ("2037", 2037),
                            ("2038", 2038),
                            ("2039", 2039),
                            ("2040", 2040),
                            ("2041", 2041),
                            ("2042", 2042),
                            ("2043", 2043),
                            ("2044", 2044),
                            ("2045", 2045),
                            ("2046", 2046),
                            ("2047", 2047),
                            ("2048", 2048),
                            ("2049", 2049),
                        ],
                        default=0,
                        max_length=4,
                        null=True,
                        verbose_name="Birthday year",
                    ),
                ),
                (
                    "birthday_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("1", "January"),
                            ("2", "February"),
                            ("3", "March"),
                            ("4", "April"),
                            ("5", "May"),
                            ("6", "June"),
                            ("7", "July"),
                            ("8", "August"),
                            ("9", "September"),
                            ("10", "October"),
                            ("11", "November"),
                            ("12", "December"),
                        ],
                        default=0,
                        max_length=2,
                        null=True,
                        verbose_name="Birthday month",
                    ),
                ),
                (
                    "birthday_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", 1),
                            ("2", 2),
                            ("3", 3),
                            ("4", 4),
                            ("5", 5),
                            ("6", 6),
                            ("7", 7),
                            ("8", 8),
                            ("9", 9),
                            ("10", 10),
                            ("11", 11),
                            ("12", 12),
                            ("13", 13),
                            ("14", 14),
                            ("15", 15),
                            ("16", 16),
                            ("17", 17),
                            ("18", 18),
                            ("19", 19),
                            ("20", 20),
                            ("21", 21),
                            ("22", 22),
                            ("23", 23),
                            ("24", 24),
                            ("25", 25),
                            ("26", 26),
                            ("27", 27),
                            ("28", 28),
                            ("29", 29),
                            ("30", 30),
                            ("31", 31),
                        ],
                        default=0,
                        max_length=2,
                        null=True,
                        verbose_name="Birthday day",
                    ),
                ),
                (
                    "p_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Insert Pcode if the child lives in Internal Settlement/Camp",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Registered child Home Address",
                    ),
                ),
                (
                    "living_arrangement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Unaccompanied", "Unaccompanied"),
                            ("Separated", "Separated"),
                            (
                                "Living with one caregivers",
                                "Living with one caregivers",
                            ),
                            ("Living with caregivers", "Living with caregivers"),
                            ("Child headed household", "Child headed household"),
                            (
                                "Married and living with extended family",
                                "Married and living with extended family",
                            ),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Child’s Living Arrangement",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Married", "Married"),
                            ("Engaged", "Engaged"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                            ("Single", "Single"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Child’s Marital Status",
                    ),
                ),
                (
                    "have_children",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Yes", "Yes"),
                            ("No", "No"),
                            (
                                "Child pregnant or expecting children",
                                "Child pregnant or expecting children",
                            ),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Does the child have children?",
                    ),
                ),
                (
                    "children_number",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, 0),
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                        ],
                        null=True,
                        verbose_name="If yes, how many?",
                    ),
                ),
                (
                    "have_sibling",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("Yes", "Yes"), ("No", "No")],
                        max_length=50,
                        null=True,
                        verbose_name="Does the child have siblings?",
                    ),
                ),
                (
                    "siblings_have_disability",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("Yes", "Yes"), ("No", "No")],
                        max_length=50,
                        null=True,
                        verbose_name="Does any of the siblings have a disability?",
                    ),
                ),
                (
                    "mother_pregnant_expecting",
                    models.CharField(
                        blank=True,
                        choices=[("", "----------"), ("Yes", "Yes"), ("No", "No")],
                        max_length=50,
                        null=True,
                        verbose_name="Is the mother pregnant or expecting?",
                    ),
                ),
                (
                    "fe_unique_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Formal Education unique student ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "unicef_id",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Unicef ID"
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="UNHCR Case number",
                    ),
                ),
                (
                    "case_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="UNHCR Case number confirm",
                    ),
                ),
                (
                    "parent_individual_case_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent individual ID",
                    ),
                ),
                (
                    "parent_individual_case_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent individual ID confirm",
                    ),
                ),
                (
                    "individual_case_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child individual ID",
                    ),
                ),
                (
                    "individual_case_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child individual ID confirm",
                    ),
                ),
                (
                    "recorded_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="UNHCR recorded barcode",
                    ),
                ),
                (
                    "recorded_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="UNHCR recorded barcode confirm",
                    ),
                ),
                (
                    "parent_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Lebanese ID number",
                    ),
                ),
                (
                    "parent_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Lebanese ID number",
                    ),
                ),
                (
                    "national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child Lebanese ID number",
                    ),
                ),
                (
                    "national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child Lebanese ID number",
                    ),
                ),
                (
                    "parent_extract_record",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Lebanese Extract of Record",
                    ),
                ),
                (
                    "parent_extract_record_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Lebanese Extract of Record confirm",
                    ),
                ),
                (
                    "parent_syrian_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Syrian ID number ",
                    ),
                ),
                (
                    "parent_syrian_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Syrian ID number confirm",
                    ),
                ),
                (
                    "syrian_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child Syrian ID number",
                    ),
                ),
                (
                    "syrian_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child Syrian ID number confirm",
                    ),
                ),
                (
                    "parent_sop_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Palestinian ID number ",
                    ),
                ),
                (
                    "parent_sop_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parent Palestinian ID number",
                    ),
                ),
                (
                    "sop_national_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child Palestinian ID number",
                    ),
                ),
                (
                    "sop_national_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Child Palestinian ID number confirm",
                    ),
                ),
                (
                    "parent_other_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID number of the Caregiver confirm",
                    ),
                ),
                (
                    "parent_other_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID number of the Caregiver",
                    ),
                ),
                (
                    "other_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID number of the child",
                    ),
                ),
                (
                    "other_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID number of the child confirm",
                    ),
                ),
                (
                    "first_phone_owner",
                    models.CharField(
                        choices=[
                            ("", "----------"),
                            ("Phone Main Caregiver", "Phone Main Caregiver"),
                            ("Family Member", "Family Member"),
                            ("Neighbors", "Neighbors"),
                            ("Shawish", "Shawish"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Who will be answering the phone?",
                    ),
                ),
                (
                    "first_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Primary phone number",
                    ),
                ),
                (
                    "first_phone_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Confirm primary phone number",
                    ),
                ),
                (
                    "second_phone_owner",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Phone Main Caregiver", "Phone Main Caregiver"),
                            ("Family Member", "Family Member"),
                            ("Neighbors", "Neighbors"),
                            ("Shawish", "Shawish"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Who will be answering the phone",
                    ),
                ),
                (
                    "second_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Secondary phone number if available",
                    ),
                ),
                (
                    "second_phone_number_confirm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Confirm Secondary phone number if available",
                    ),
                ),
                (
                    "main_caregiver",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----------"),
                            ("Mother", "Mother"),
                            ("Father", "Father"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="who is the Child primary caregiver?",
                    ),
                ),
                (
                    "main_caregiver_other",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                (
                    "children_number_under18",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Number of children (under 18) living in the household",
                    ),
                ),
                (
                    "caregiver_first_name",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Caregiver First Name"
                    ),
                ),
                (
                    "caregiver_middle_name",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Caregiver Middle Name"
                    ),
                ),
                (
                    "caregiver_last_name",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Caregiver Last Name"
                    ),
                ),
                (
                    "caregiver_mother_name",
                    models.CharField(
                        max_length=500,
                        null=True,
                        verbose_name="Caregiver  Mother Full Name",
                    ),
                ),
                (
                    "main_caregiver_nationality_other",
                    models.TextField(
                        blank=True, null=True, verbose_name="Please specify"
                    ),
                ),
                ("cash_programmes", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
