# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("child", "0001_initial"),
        ("clm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="disability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clm.disability",
                verbose_name="Does the child have any disability or special need?",
            ),
        ),
    ]
