# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("child", "0002_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="father_educational_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.educationallevel",
                verbose_name="What is the father's educational level?",
            ),
        ),
    ]
