# Generated by Django 5.2.7 on 2025-11-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("child", "0003_initial"),
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="id_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="students.idtype",
                verbose_name="Child ID type",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="main_caregiver_nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="students.nationality",
                verbose_name="Caregiver Nationality",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="mother_educational_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.educationallevel",
                verbose_name="What is the father's educational level?",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="students.nationality",
                verbose_name="Nationality",
            ),
        ),
    ]
