# Generated by Django 5.2.7 on 2026-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_alter_child_unicef_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='building_camp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Building/Camp (مبنى/مخيم)'),
        ),
        migrations.AddField(
            model_name='child',
            name='cadaster',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cadaster (منطقة عقارية)'),
        ),
        migrations.AddField(
            model_name='child',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='District/Caza (قضاء)'),
        ),
        migrations.AddField(
            model_name='child',
            name='governorate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Governorate (محافظة)'),
        ),
        migrations.AddField(
            model_name='child',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipality (بلدية)'),
        ),
        migrations.AddField(
            model_name='child',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street (شارع)'),
        ),
        migrations.AddField(
            model_name='child',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Village (قرية)'),
        ),
    ]
