# Generated by Django 5.2.7 on 2026-10-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_alter_child_unicef_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='bma_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='BMA child ID'),
        ),
    ]
